version: 2.1

jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - run: rustup component add rust-src llvm-tools-preview
      - checkout
      - restore_cache:
          keys:
            - cargo-build-cache-{{ checksum ".ci/install-or-update-rust-deps.sh" }}-{{ .Environment.CACHE_VERSION }}
            - cargo-build-cache-{{ checksum ".ci/install-or-update-rust-deps.sh" }}
            - cargo-build-cache
      - run: CARGO_HOME=$PWD/cargo .ci/install-or-update-rust-deps.sh
      - run: CARGO_HOME=$PWD/cargo make
      - save_cache:
          key: cargo-build-cache-{{ checksum ".ci/install-or-update-rust-deps.sh" }}-{{ .Environment.CACHE_VERSION }}
          paths:
            - cargo

  test:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - run: rustup component add rust-src
      - checkout
      - run: make test

  lint:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-lint-cache-{{ checksum ".ci/install-or-update-rust-deps.sh" }}-{{ .Environment.CACHE_VERSION }}
            - cargo-lint-cache-{{ checksum ".ci/install-or-update-rust-deps.sh" }}
            - cargo-lint-cache
      - run: rustup component add rust-src
      - run: rustup component add rustfmt || CARGO_HOME=/cargo-cache cargo install --git https://github.com/rust-lang/rustfmt/ --force rustfmt
      - run: rustup component add clippy || CARGO_HOME=/cargo-cache cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
      - run: CARGO_HOME=/cargo-cache .ci/install-or-update-rust-deps.sh
      - run: make format
      - run: CARGO_HOME=/cargo-cache make clippy
      - save_cache:
          key: cargo-lint-cache-{{ checksum ".ci/install-or-update-rust-deps.sh" }}-{{ .Environment.CACHE_VERSION }}
          paths:
            - /cargo-cache

workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - test
      - lint
